name: Build and Deploy Docker Image to Azure Container Registry (ACR)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx (for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to Azure Container Registry (ACR)
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    # Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/myapp:latest .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      # Deploy Docker image to Azure Web App (or other Azure services)
      - name: Deploy Docker container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-azure-web-app'  # Replace with your Azure Web App name
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/myapp:latest
