name: Build and Deploy Docker Image to Azure Container Registry (ACR)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Check if Docker is installed and get its version
      - name: Check Docker installation
        run: |
          docker --version
          docker info

      # Install Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest  # Ensure you are using the latest version of Buildx

      # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}  # Azure Service Principal client ID
          password: ${{ secrets.AZURE_CLIENT_SECRET }}  # Azure Service Principal client secret

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker buildx create --use # Ensure Buildx is initialized and used
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/myapp:latest .
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/myapp:latest

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      # Deploy Docker image to Azure Web App
      - name: Deploy Docker container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-azure-web-app'  # Replace with your Azure Web App name
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/myapp:latest
